### PR TITLE
`as_quaternion()` function implementation and tests

### PR DESCRIPTION
**Pull request by adbugger**
Implemented, documented, and added test cases for, `as_quaternion` function.

### CODE REVIEW

**Comment by nmayorov** [comment]
Looks good to be merged. 

Before moving on to matrices, I noticed a small misconception in naming you have --- DCM is *Direction* Cosine Matrix.

**Comment by adbugger** [comment]
It looks like an unrelated example failed. I'm just curious as to why that can happen sometimes.

**Comment by nmayorov** [comment]
Well, I would guess that there is some non-determinism exists in difficult routines from BLAS/LAPACK.

**Comment by larsoner** [comment]
Yeah from time to time little bugs like this show up where tests need a looser numerical tolerance.

If you merge / rebase your `master` with `upstream/master` it will probably go away.

**Pull request merged**
